version: "3"

tasks:
  default: task --list-all
  argo:password: echo "Bearer $(kubectl get secret -n argo default.service-account-token -o=jsonpath='{.data.token}' | base64 --decode)"
  argo:port-forward: kubectl port-forward -n argo svc/argo-server 2746:2746
  argocd:password: echo "$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)"
  argocd:port-forward: kubectl port-forward svc/argocd-server -n argocd 8080:443
  update-kubeconfig:
    dir: terraform
    cmd: aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)
  ###
  api:deps: cargo install systemfd cargo-watch
  api:dev:
    dir: crates/api
    deps: 
      - api:deps
    cmd: systemfd --no-pid -s http::8080 -- cargo watch -x run
  api:build-image: pack build scan-automate-api -b docker.io/paketocommunity/rust -B paketobuildpacks/builder-jammy-base
  ###
  up: 
    deps:
      - api:build-image
    cmd: ./bin/up.sh