version: "3"

tasks:
  default: task --list-all
  install:deps: cargo install systemfd cargo-watch
  api:dev: 
    dep: install:deps
    cmd: systemfd --no-pid -s http::4000 -- cargo watch -x run
  api:build-image: pack build scan-automate-api -b docker.io/paketocommunity/rust
  k8s:delete: minikube delete -p fncyber
  k8s:up:
    deps:
      - k8s:delete
    cmd: minikube start --driver=docker --cpus=6 --memory=6g -p fncyber
  k8s:tunnel: minikube tunnel -p fncyber --bind-address 0.0.0.0
  k8s:down: minikube stop -p fncyber
  k8s:provision: ./bin/k8s-provision.sh
  cf-tunnel:
    vars:
      NS: cloudflared
    cmds:
      - kubectl create ns {{.NS}} --dry-run=client -o yaml | kubectl apply -f -
      - kubectl apply -k k8s/kustomize/cloudflared -n {{.NS}}
      - kubectl create secret generic cloudflare-config --from-literal=TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN --dry-run=client -o yaml | kubectl apply -n {{.NS}} -f -
  argo-password: echo "Bearer $(kubectl get secret -n argo default.service-account-token -o=jsonpath='{.data.token}' | base64 --decode)"
  argocd-password: echo "$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)"
  grafana-port-forward: ebort -- kubectl port-forward -n monitoring svc/kube-prometheus-stack-grafana 3000:80 2> /dev/null
  update-kubeconfig:
    dir: terraform
    cmd: aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)

