apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scan-workflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
  source:
    path: scan-automate/k8s/kustomize/scan-workflow
    repoURL: "https://github.com/audacioustux/fncyber"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
