services:
  devcontainer:
    build:
      context: .
    environment:
      - GIT_TOKEN
      - GIT_USERNAME
      - DOCKER_USERNAME
      - DOCKER_TOKEN
      - CLOUDFLARE_TUNNEL_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - SMTP_HOST
      - SMTP_USERNAME
      - SMTP_PASSWORD
    volumes:
      - ../..:/workspaces:rw,cached
    init: true

    command: sleep infinity
