kind: Deployment
apiVersion: apps/v1
metadata:
  name: scan-automate
spec:
  selector:
    matchLabels:
      app: scan-automate
  template:
    metadata:
      labels:
        app: scan-automate
    spec:
      containers:
        - name: scan-automate
          image: tanjim/scan-automate-api
          ports:
            - name: http
              containerPort: 4000
          envFrom:
            - secretRef:
                name: scan-automate-api
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
