apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: scan-workflow
  namespace: argo-events
spec:
  service:
    ports:
      - port: 8082
        targetPort: 8082
  webhook:
    scan-workflow:
      port: "8082"
      endpoint: /
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  dependencies:
    - name: scan-workflow
      eventSourceName: scan-workflow
      eventName: scan-workflow
  triggers:
    - template:
        name: scan-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: argo
              spec:
                arguments:
                  parameters:
                    - name: email
                    - name: rustscan
                    - name: zap
                workflowTemplateRef:
                  name: scan-workflow
          parameters:
            - src:
                dependencyName: scan-workflow
                dataKey: body.email
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: scan-workflow
                dataKey: body.rustscan
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: scan-workflow
                dataKey: body.zap
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: scan-workflow
                dataTemplate: "scan-{{ .Input.body.id }}"
              dest: metadata.name
