apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: scan-workflow
  namespace: argo
spec:
  generateName: scan-
  entrypoint: scan
  artifactGC:
    strategy: OnWorkflowDeletion
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi
  arguments:
    parameters:
      - name: url
      - name: email
      - name: scans
  templates:
    - name: scan
      dag:
        tasks:
          - name: rustscan
            template: rustscan
            # when rustscan is in `scans` array
            # when: "{{ contains(workflow.parameters.scans, 'rustscan') }}"
    - name: rustscan
      container:
        image: rustscan/rustscan:latest
        args:
          - "-a {{workflow.parameters.url}}"
  volumes:
    - name: docker-config
      secret:
        secretName: docker-config
        # create docker-config secret with `kubectl create secret generic docker-config --from-file=$HOME/.docker/config.json`