apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: scan-workflow
  namespace: argo
spec:
  generateName: scan-
  entrypoint: scan
  retryStrategy:
   retryPolicy: OnError
   limit: 1
  artifactGC:
    strategy: OnWorkflowDeletion
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 256Mi
        storageClassName: aws-efs
  arguments:
    parameters:
      - name: id
      - name: email
      - name: rustscan
      - name: zap
  templates:
    - name: scan
      dag:
        tasks:
          - name: rustscan
            template: rustscan
            when: "{{=workflow.parameters.rustscan != ''}}"
          - name: zap
            template: zap
            when: "{{=workflow.parameters.zap != ''}}"
          - name: gen-pdf
            template: gen-pdf
            dependencies:
              - rustscan
              - zap
          - name: get-signed-url
            template: get-signed-url
            dependencies:
              - gen-pdf
          - name: send-signed-url
            template: send-signed-url
            dependencies:
              - get-signed-url
    - name: rustscan
      inputs:
        parameters:
          - name: uri
            value: "{{=jsonpath(workflow.parameters.rustscan, '$.uri')}}"
      container:
        image: rustscan/rustscan:2.1.1
        command: ["/bin/sh"]
        args:
          - -c
          - |
            # set explicit ulimit
            ulimit -n 5100
            # canonicalize url
            uri=$(echo -n {{inputs.parameters.uri}} | sed -e 's/http[s]*:\/\///g')
            # run rustscan
            # add two spaces to the end of each line to prevent pandoc from interpreting the markdown
            rustscan -r 1-65535 -t 5000 -b 5000 --accessible -a $uri | sed 's/$/  /' > rustscan-report.md
        workingDir: /workdir
        volumeMounts:
          - name: workdir
            mountPath: /workdir
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 500Mi
            cpu: 500m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
    - name: zap
      inputs:
        parameters:
          - name: uri
            value: "{{=jsonpath(workflow.parameters.zap, '$.uri')}}"
      container:
        image: ghcr.io/zaproxy/zaproxy:2.14.0
        command: ["/bin/sh"]
        args:
          - -c
          - |
            # run zap-baseline
            zap-baseline.py -t "{{inputs.parameters.uri}}" -w zap-report.md -I
            # whitelabel report
            sed -i 's/Zap/Fncyber/gi' zap-report.md
        workingDir: /zap/wrk
        volumeMounts:
          - name: workdir
            mountPath: /zap/wrk
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 500Mi
            cpu: 500m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
    - name: gen-pdf
      container:
        image: pandoc/latex:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            # concatenate reports
            cat *-report.* > report.md
            # generate pdf
            pandoc report.md -o report-{{workflow.parameters.id}}.pdf
        workingDir: /workdir
        volumeMounts:
          - name: workdir
            mountPath: /workdir
        resources:
          limits:
            memory: 1Gi
            cpu: 0.5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      outputs:
        artifacts:
          - name: output
            path: /workdir/report-{{workflow.parameters.id}}.pdf
            archive:
              none: {}
            s3:
              endpoint: s3.amazonaws.com
              bucket: "scan-automate-reports"
              createBucketIfNotPresent:
                enabled: true
              key: report-{{workflow.parameters.id}}.pdf
              accessKeySecret:
                name: aws-config
                key: AWS_ACCESS_KEY_ID
              secretKeySecret:
                name: aws-config
                key: AWS_SECRET_ACCESS_KEY
    - name: get-signed-url
      container:
        image: amazon/aws-cli:latest
        command: aws s3 presign s3://scan-automate-reports/report-{{workflow.parameters.id}}.pdf --expires-in 604800 > /tmp/outputs/signed-url.txt
        envFrom:
          - secretRef:
              name: aws-config
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      outputs:
        parameters:
          - name: signed-url
            valueFrom:
              path: /tmp/outputs/signed-url.txt
    - name: send-signed-url
      inputs:
        parameters:
          - name: email
            value: "{{workflow.parameters.email}}"
          - name: signed-url
            value: "{{tasks.get-signed-url.outputs.parameters.signed-url}}"
      container:
        image: tanjim/lettre-smtp:latest
        args:
          - "--mail-to"
          - "{{inputs.parameters.email}}"
          - "--subject"
          - "Scan Report for {{workflow.parameters.id}}"
          - "--body" 
          - "{{inputs.parameters.signed-url}}"
        envFrom:
          - secretRef:
              name: smtp-config
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
  volumes:
    - name: docker-config
      secret:
        secretName: docker-config
