apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-events/releases/download/v1.8.1/install.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml
  - rbac.yaml